### PR TITLE
Swagger Documentation

### PR DESCRIPTION
**Pull request by Nicanor008**
### **What does this PR do?**
Writes descriptive documentation of the Product Investo API endpoints

### ** Description of Task to be completed?**
- yamljs & swagger-ui-express package
- docs file
- corrected simple spelling errors

### **How should this be manually tested?**
- Clone this repo, install dependencies, `npm install`
- checkout into this branch, `git checkout ch-documentation-173306658`
- run the development server, `npm run dev`
- Open a new tab on your favorite browser, `http://localhost:{port}/docs` use your port number

### **Any background context you want to provide?**

- None 

### **What are the relevant PT Story ID?**

[#173306658](https://www.pivotaltracker.com/story/show/173306658)

#### Swagger UI on Chrome Browser
Screenshot 2020-07-01 at 18 19 31

**Questions:**

- None

### CODE REVIEW

**Comment by neymarjimoh** [comment]
It's working fine . Just trying to familiarize myself with the swagger documentation keywords and how to structure them

**Comment by neymarjimoh** [comment]
ok. Thanks for the review .. i'll make the necessary updates

**Comment by neymarjimoh** [comment]
After pulling your changes locally, i can't use `git commit --amend` or `git commit --amend --no-edit` 
i'm required to comment something before it can merge

**Comment by Nicanor008** [comment]
> After pulling your changes locally, I can't use `git commit --amend` or `git commit --amend --no-edit`
> I'm required to comment something before it can merge

Oooohh it's okay, just use your merge message

**Comment by neymarjimoh** [comment]
I used DRY practices for some response messages and the bearer token parameter

**Pull request merged**
